# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_keyboard.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote_keyboard.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\tGenerated'),
  serialized_pb=_b('\n\x15remote_keyboard.proto\"4\n\x10KeyPressResponse\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\"#\n\x0fKeyPressRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t2U\n\x15RemoteKeyboardService\x12<\n\x11SendKeyboardCalls\x12\x10.KeyPressRequest\x1a\x11.KeyPressResponse(\x01\x30\x01\x42\x0c\xaa\x02\tGeneratedb\x06proto3')
)




_KEYPRESSRESPONSE = _descriptor.Descriptor(
  name='KeyPressResponse',
  full_name='KeyPressResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_name', full_name='KeyPressResponse.key_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='KeyPressResponse.result', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=77,
)


_KEYPRESSREQUEST = _descriptor.Descriptor(
  name='KeyPressRequest',
  full_name='KeyPressRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_name', full_name='KeyPressRequest.key_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['KeyPressResponse'] = _KEYPRESSRESPONSE
DESCRIPTOR.message_types_by_name['KeyPressRequest'] = _KEYPRESSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyPressResponse = _reflection.GeneratedProtocolMessageType('KeyPressResponse', (_message.Message,), dict(
  DESCRIPTOR = _KEYPRESSRESPONSE,
  __module__ = 'remote_keyboard_pb2'
  # @@protoc_insertion_point(class_scope:KeyPressResponse)
  ))
_sym_db.RegisterMessage(KeyPressResponse)

KeyPressRequest = _reflection.GeneratedProtocolMessageType('KeyPressRequest', (_message.Message,), dict(
  DESCRIPTOR = _KEYPRESSREQUEST,
  __module__ = 'remote_keyboard_pb2'
  # @@protoc_insertion_point(class_scope:KeyPressRequest)
  ))
_sym_db.RegisterMessage(KeyPressRequest)


DESCRIPTOR._options = None

_REMOTEKEYBOARDSERVICE = _descriptor.ServiceDescriptor(
  name='RemoteKeyboardService',
  full_name='RemoteKeyboardService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=116,
  serialized_end=201,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendKeyboardCalls',
    full_name='RemoteKeyboardService.SendKeyboardCalls',
    index=0,
    containing_service=None,
    input_type=_KEYPRESSREQUEST,
    output_type=_KEYPRESSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTEKEYBOARDSERVICE)

DESCRIPTOR.services_by_name['RemoteKeyboardService'] = _REMOTEKEYBOARDSERVICE

# @@protoc_insertion_point(module_scope)
