# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_mouse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote_mouse.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\tGenerated'),
  serialized_pb=_b('\n\x12remote_mouse.proto\"\'\n\x15MouseMovementResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\",\n\x14MouseMovementRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"M\n\x11MouseClickRequest\x12\x1b\n\x06\x62utton\x18\x01 \x01(\x0e\x32\x0b.ButtonType\x12\x1b\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x0b.ActionType\"$\n\x12MouseClickResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08*4\n\nButtonType\x12\x11\n\rInvalidButton\x10\x00\x12\x08\n\x04Left\x10\x01\x12\t\n\x05Right\x10\x02*7\n\nActionType\x12\x11\n\rInvalidAction\x10\x00\x12\t\n\x05Press\x10\x01\x12\x0b\n\x07Release\x10\x02\x32\x93\x01\n\x12RemoteMouseService\x12\x42\n\x11SendMouseMovement\x12\x15.MouseMovementRequest\x1a\x16.MouseMovementResponse\x12\x39\n\x0eSendMouseClick\x12\x12.MouseClickRequest\x1a\x13.MouseClickResponseB\x0c\xaa\x02\tGeneratedb\x06proto3')
)

_BUTTONTYPE = _descriptor.EnumDescriptor(
  name='ButtonType',
  full_name='ButtonType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='InvalidButton', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Left', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Right', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=226,
  serialized_end=278,
)
_sym_db.RegisterEnumDescriptor(_BUTTONTYPE)

ButtonType = enum_type_wrapper.EnumTypeWrapper(_BUTTONTYPE)
_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='InvalidAction', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Press', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Release', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=280,
  serialized_end=335,
)
_sym_db.RegisterEnumDescriptor(_ACTIONTYPE)

ActionType = enum_type_wrapper.EnumTypeWrapper(_ACTIONTYPE)
InvalidButton = 0
Left = 1
Right = 2
InvalidAction = 0
Press = 1
Release = 2



_MOUSEMOVEMENTRESPONSE = _descriptor.Descriptor(
  name='MouseMovementResponse',
  full_name='MouseMovementResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='MouseMovementResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=61,
)


_MOUSEMOVEMENTREQUEST = _descriptor.Descriptor(
  name='MouseMovementRequest',
  full_name='MouseMovementRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='MouseMovementRequest.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='MouseMovementRequest.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=107,
)


_MOUSECLICKREQUEST = _descriptor.Descriptor(
  name='MouseClickRequest',
  full_name='MouseClickRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='button', full_name='MouseClickRequest.button', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='MouseClickRequest.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=186,
)


_MOUSECLICKRESPONSE = _descriptor.Descriptor(
  name='MouseClickResponse',
  full_name='MouseClickResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='MouseClickResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=224,
)

_MOUSECLICKREQUEST.fields_by_name['button'].enum_type = _BUTTONTYPE
_MOUSECLICKREQUEST.fields_by_name['action'].enum_type = _ACTIONTYPE
DESCRIPTOR.message_types_by_name['MouseMovementResponse'] = _MOUSEMOVEMENTRESPONSE
DESCRIPTOR.message_types_by_name['MouseMovementRequest'] = _MOUSEMOVEMENTREQUEST
DESCRIPTOR.message_types_by_name['MouseClickRequest'] = _MOUSECLICKREQUEST
DESCRIPTOR.message_types_by_name['MouseClickResponse'] = _MOUSECLICKRESPONSE
DESCRIPTOR.enum_types_by_name['ButtonType'] = _BUTTONTYPE
DESCRIPTOR.enum_types_by_name['ActionType'] = _ACTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MouseMovementResponse = _reflection.GeneratedProtocolMessageType('MouseMovementResponse', (_message.Message,), dict(
  DESCRIPTOR = _MOUSEMOVEMENTRESPONSE,
  __module__ = 'remote_mouse_pb2'
  # @@protoc_insertion_point(class_scope:MouseMovementResponse)
  ))
_sym_db.RegisterMessage(MouseMovementResponse)

MouseMovementRequest = _reflection.GeneratedProtocolMessageType('MouseMovementRequest', (_message.Message,), dict(
  DESCRIPTOR = _MOUSEMOVEMENTREQUEST,
  __module__ = 'remote_mouse_pb2'
  # @@protoc_insertion_point(class_scope:MouseMovementRequest)
  ))
_sym_db.RegisterMessage(MouseMovementRequest)

MouseClickRequest = _reflection.GeneratedProtocolMessageType('MouseClickRequest', (_message.Message,), dict(
  DESCRIPTOR = _MOUSECLICKREQUEST,
  __module__ = 'remote_mouse_pb2'
  # @@protoc_insertion_point(class_scope:MouseClickRequest)
  ))
_sym_db.RegisterMessage(MouseClickRequest)

MouseClickResponse = _reflection.GeneratedProtocolMessageType('MouseClickResponse', (_message.Message,), dict(
  DESCRIPTOR = _MOUSECLICKRESPONSE,
  __module__ = 'remote_mouse_pb2'
  # @@protoc_insertion_point(class_scope:MouseClickResponse)
  ))
_sym_db.RegisterMessage(MouseClickResponse)


DESCRIPTOR._options = None

_REMOTEMOUSESERVICE = _descriptor.ServiceDescriptor(
  name='RemoteMouseService',
  full_name='RemoteMouseService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=338,
  serialized_end=485,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMouseMovement',
    full_name='RemoteMouseService.SendMouseMovement',
    index=0,
    containing_service=None,
    input_type=_MOUSEMOVEMENTREQUEST,
    output_type=_MOUSEMOVEMENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendMouseClick',
    full_name='RemoteMouseService.SendMouseClick',
    index=1,
    containing_service=None,
    input_type=_MOUSECLICKREQUEST,
    output_type=_MOUSECLICKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTEMOUSESERVICE)

DESCRIPTOR.services_by_name['RemoteMouseService'] = _REMOTEMOUSESERVICE

# @@protoc_insertion_point(module_scope)
