# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensors.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\tGenerated'),
  serialized_pb=_b('\n\rsensors.proto\"N\n\x17SensorAirQualityRequest\x12$\n\x0b\x61ir_feature\x18\x01 \x01(\x0e\x32\x0f.AirFeatureType\x12\r\n\x05value\x18\x02 \x01(\x01\":\n\x18SensorAirQualityResponse\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.RequestStatus\"_\n\x18SensorEnvironmentRequest\x12\x34\n\x13\x65nvironment_feature\x18\x01 \x01(\x0e\x32\x17.EnvironmentFeatureType\x12\r\n\x05value\x18\x02 \x01(\x01\";\n\x19SensorEnvironmentResponse\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.RequestStatus*^\n\rRequestStatus\x12\x18\n\x14InvalidRequestStatus\x10\x00\x12\x0c\n\x08RECEIVED\x10\x01\x12\x0c\n\x08RESOLVED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\x0b\n\x07TIMEOUT\x10\x04*;\n\x0e\x41irFeatureType\x12\x15\n\x11InvalidAirFeature\x10\x00\x12\x08\n\x04\x65\x43O2\x10\x01\x12\x08\n\x04TVOC\x10\x02*{\n\x16\x45nvironmentFeatureType\x12\x1d\n\x19InvalidEnvironmentFeature\x10\x00\x12\x0f\n\x0bTEMPERATURE\x10\x01\x12\x07\n\x03GAS\x10\x02\x12\x0c\n\x08HUMIDITY\x10\x03\x12\x0c\n\x08PRESSURE\x10\x04\x12\x0c\n\x08\x41LTITUDE\x10\x05\x32\xac\x01\n\x17SensorAirQualityService\x12\x45\n\x0eSendAirFeature\x12\x18.SensorAirQualityRequest\x1a\x19.SensorAirQualityResponse\x12J\n\x0fSendAirFeatures\x12\x18.SensorAirQualityRequest\x1a\x19.SensorAirQualityResponse(\x01\x30\x01\x32\xc1\x01\n\x18SensorEnvironmentService\x12O\n\x16SendEnvironmentFeature\x12\x19.SensorEnvironmentRequest\x1a\x1a.SensorEnvironmentResponse\x12T\n\x17SendEnvironmentFeatures\x12\x19.SensorEnvironmentRequest\x1a\x1a.SensorEnvironmentResponse(\x01\x30\x01\x42\x0c\xaa\x02\tGeneratedb\x06proto3')
)

_REQUESTSTATUS = _descriptor.EnumDescriptor(
  name='RequestStatus',
  full_name='RequestStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='InvalidRequestStatus', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECEIVED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESOLVED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=315,
  serialized_end=409,
)
_sym_db.RegisterEnumDescriptor(_REQUESTSTATUS)

RequestStatus = enum_type_wrapper.EnumTypeWrapper(_REQUESTSTATUS)
_AIRFEATURETYPE = _descriptor.EnumDescriptor(
  name='AirFeatureType',
  full_name='AirFeatureType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='InvalidAirFeature', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eCO2', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TVOC', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=411,
  serialized_end=470,
)
_sym_db.RegisterEnumDescriptor(_AIRFEATURETYPE)

AirFeatureType = enum_type_wrapper.EnumTypeWrapper(_AIRFEATURETYPE)
_ENVIRONMENTFEATURETYPE = _descriptor.EnumDescriptor(
  name='EnvironmentFeatureType',
  full_name='EnvironmentFeatureType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='InvalidEnvironmentFeature', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEMPERATURE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HUMIDITY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRESSURE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALTITUDE', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=472,
  serialized_end=595,
)
_sym_db.RegisterEnumDescriptor(_ENVIRONMENTFEATURETYPE)

EnvironmentFeatureType = enum_type_wrapper.EnumTypeWrapper(_ENVIRONMENTFEATURETYPE)
InvalidRequestStatus = 0
RECEIVED = 1
RESOLVED = 2
FAILED = 3
TIMEOUT = 4
InvalidAirFeature = 0
eCO2 = 1
TVOC = 2
InvalidEnvironmentFeature = 0
TEMPERATURE = 1
GAS = 2
HUMIDITY = 3
PRESSURE = 4
ALTITUDE = 5



_SENSORAIRQUALITYREQUEST = _descriptor.Descriptor(
  name='SensorAirQualityRequest',
  full_name='SensorAirQualityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='air_feature', full_name='SensorAirQualityRequest.air_feature', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='SensorAirQualityRequest.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=95,
)


_SENSORAIRQUALITYRESPONSE = _descriptor.Descriptor(
  name='SensorAirQualityResponse',
  full_name='SensorAirQualityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SensorAirQualityResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=155,
)


_SENSORENVIRONMENTREQUEST = _descriptor.Descriptor(
  name='SensorEnvironmentRequest',
  full_name='SensorEnvironmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='environment_feature', full_name='SensorEnvironmentRequest.environment_feature', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='SensorEnvironmentRequest.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=252,
)


_SENSORENVIRONMENTRESPONSE = _descriptor.Descriptor(
  name='SensorEnvironmentResponse',
  full_name='SensorEnvironmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SensorEnvironmentResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=313,
)

_SENSORAIRQUALITYREQUEST.fields_by_name['air_feature'].enum_type = _AIRFEATURETYPE
_SENSORAIRQUALITYRESPONSE.fields_by_name['status'].enum_type = _REQUESTSTATUS
_SENSORENVIRONMENTREQUEST.fields_by_name['environment_feature'].enum_type = _ENVIRONMENTFEATURETYPE
_SENSORENVIRONMENTRESPONSE.fields_by_name['status'].enum_type = _REQUESTSTATUS
DESCRIPTOR.message_types_by_name['SensorAirQualityRequest'] = _SENSORAIRQUALITYREQUEST
DESCRIPTOR.message_types_by_name['SensorAirQualityResponse'] = _SENSORAIRQUALITYRESPONSE
DESCRIPTOR.message_types_by_name['SensorEnvironmentRequest'] = _SENSORENVIRONMENTREQUEST
DESCRIPTOR.message_types_by_name['SensorEnvironmentResponse'] = _SENSORENVIRONMENTRESPONSE
DESCRIPTOR.enum_types_by_name['RequestStatus'] = _REQUESTSTATUS
DESCRIPTOR.enum_types_by_name['AirFeatureType'] = _AIRFEATURETYPE
DESCRIPTOR.enum_types_by_name['EnvironmentFeatureType'] = _ENVIRONMENTFEATURETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorAirQualityRequest = _reflection.GeneratedProtocolMessageType('SensorAirQualityRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENSORAIRQUALITYREQUEST,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:SensorAirQualityRequest)
  })
_sym_db.RegisterMessage(SensorAirQualityRequest)

SensorAirQualityResponse = _reflection.GeneratedProtocolMessageType('SensorAirQualityResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENSORAIRQUALITYRESPONSE,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:SensorAirQualityResponse)
  })
_sym_db.RegisterMessage(SensorAirQualityResponse)

SensorEnvironmentRequest = _reflection.GeneratedProtocolMessageType('SensorEnvironmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENSORENVIRONMENTREQUEST,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:SensorEnvironmentRequest)
  })
_sym_db.RegisterMessage(SensorEnvironmentRequest)

SensorEnvironmentResponse = _reflection.GeneratedProtocolMessageType('SensorEnvironmentResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENSORENVIRONMENTRESPONSE,
  '__module__' : 'sensors_pb2'
  # @@protoc_insertion_point(class_scope:SensorEnvironmentResponse)
  })
_sym_db.RegisterMessage(SensorEnvironmentResponse)


DESCRIPTOR._options = None

_SENSORAIRQUALITYSERVICE = _descriptor.ServiceDescriptor(
  name='SensorAirQualityService',
  full_name='SensorAirQualityService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=598,
  serialized_end=770,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendAirFeature',
    full_name='SensorAirQualityService.SendAirFeature',
    index=0,
    containing_service=None,
    input_type=_SENSORAIRQUALITYREQUEST,
    output_type=_SENSORAIRQUALITYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendAirFeatures',
    full_name='SensorAirQualityService.SendAirFeatures',
    index=1,
    containing_service=None,
    input_type=_SENSORAIRQUALITYREQUEST,
    output_type=_SENSORAIRQUALITYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENSORAIRQUALITYSERVICE)

DESCRIPTOR.services_by_name['SensorAirQualityService'] = _SENSORAIRQUALITYSERVICE


_SENSORENVIRONMENTSERVICE = _descriptor.ServiceDescriptor(
  name='SensorEnvironmentService',
  full_name='SensorEnvironmentService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=773,
  serialized_end=966,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendEnvironmentFeature',
    full_name='SensorEnvironmentService.SendEnvironmentFeature',
    index=0,
    containing_service=None,
    input_type=_SENSORENVIRONMENTREQUEST,
    output_type=_SENSORENVIRONMENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendEnvironmentFeatures',
    full_name='SensorEnvironmentService.SendEnvironmentFeatures',
    index=1,
    containing_service=None,
    input_type=_SENSORENVIRONMENTREQUEST,
    output_type=_SENSORENVIRONMENTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENSORENVIRONMENTSERVICE)

DESCRIPTOR.services_by_name['SensorEnvironmentService'] = _SENSORENVIRONMENTSERVICE

# @@protoc_insertion_point(module_scope)
