# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import air_quality_pb2 as air__quality__pb2


class AirQualityServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAirQuality = channel.unary_unary(
        '/AirQualityService/GetAirQuality',
        request_serializer=air__quality__pb2.AirQualityRequest.SerializeToString,
        response_deserializer=air__quality__pb2.AirQualityResponse.FromString,
        )
    self.GetAirFeatures = channel.stream_stream(
        '/AirQualityService/GetAirFeatures',
        request_serializer=air__quality__pb2.AirQualityRequest.SerializeToString,
        response_deserializer=air__quality__pb2.AirQualityResponse.FromString,
        )


class AirQualityServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAirQuality(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAirFeatures(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AirQualityServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAirQuality': grpc.unary_unary_rpc_method_handler(
          servicer.GetAirQuality,
          request_deserializer=air__quality__pb2.AirQualityRequest.FromString,
          response_serializer=air__quality__pb2.AirQualityResponse.SerializeToString,
      ),
      'GetAirFeatures': grpc.stream_stream_rpc_method_handler(
          servicer.GetAirFeatures,
          request_deserializer=air__quality__pb2.AirQualityRequest.FromString,
          response_serializer=air__quality__pb2.AirQualityResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AirQualityService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
