# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import remote_keyboard_pb2 as remote__keyboard__pb2


class RemoteKeyboardServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendKeyboardCall = channel.unary_unary(
        '/RemoteKeyboardService/SendKeyboardCall',
        request_serializer=remote__keyboard__pb2.KeyPressRequest.SerializeToString,
        response_deserializer=remote__keyboard__pb2.KeyPressResponse.FromString,
        )


class RemoteKeyboardServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendKeyboardCall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RemoteKeyboardServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendKeyboardCall': grpc.unary_unary_rpc_method_handler(
          servicer.SendKeyboardCall,
          request_deserializer=remote__keyboard__pb2.KeyPressRequest.FromString,
          response_serializer=remote__keyboard__pb2.KeyPressResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RemoteKeyboardService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
